name: Continuous Delivery

on:
  push:
    branches:
      - "master"
    paths:
      - "src/main/java/**/*.java"
      - "src/test/java/**/*.java"
      - "!.gitattributes"
      - "!.gitignore"
      - "!README.md"
      - "!README"
      - "!LICENSE"
      - "!COPYING"
      - "pom.xml"
  pull_request:
    branches:
      - "master"
    paths:
      - "src/main/java/**/*.java"
      - "src/test/java/**/*.java"
      - "!.gitattributes"
      - "!.gitignore"
      - "!README.md"
      - "!README"
      - "!LICENSE"
      - "!COPYING"
      - "pom.xml"
  workflow_dispatch:


defaults:
  run:
    shell: bash


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 8
          cache: "maven"

      - name: Build
        run: mvn -B -V -e -ntp -Dstyle.color=always clean verify

      - name: Write test report
        uses: mikepenz/action-junit-report@v5
        if: ${{ success() || failure() }}
        with:
          report_paths: ./target/surefire-reports/TEST-*.xml
          include_passed: true
          detailed_summary: true
          fail_on_failure: true
          require_tests: true
          check_name: Test Report (${{ matrix.os }})
          check_title_template: '{{SUITE_NAME}} | {{TEST_NAME}}'

      - name: Release
        id: release
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          mvn_project_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "$mvn_project_version"
          if [[ "$mvn_project_version" == *-SNAPSHOT ]]; then
            echo "snapshot=true" >> $GITHUB_OUTPUT
            echo "Snapshot"
          else
            echo "snapshot=false" >> $GITHUB_OUTPUT
            echo "Release"
          fi

      - name: Publish package
        run: |
          if [[ "${{ steps.release.outputs.snapshot }}" == 'true' ]]; then
            export COLOSSEUM_MAVEN_URL="${{ secrets.COLOSSEUM_MAVEN }}"
          else
            export COLOSSEUM_MAVEN_URL="${{ secrets.COLOSSEUM_MAVEN_RELEASE }}"
          fi
          ./_publish.sh
        if: ${{ matrix.os == 'ubuntu-latest' && github.ref_name == 'master' && (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && steps.release.outputs.snapshot == 'true')) }}
        env:
          COLOSSEUM_MAVEN_USERNAME: ${{ secrets.COLOSSEUM_MAVEN_USERNAME }}
          COLOSSEUM_MAVEN_PASSWORD: ${{ secrets.COLOSSEUM_MAVEN_PASSWORD }}